//
//  AMS.swift
//  QCourse
//
//  Created by Qing-Cheng Li on 2019/9/5.
//  Generated by script
//  Copyright © 2019 Qing-Cheng Li. All rights reserved.
//

import Foundation

open class AMS: Airport {
    override open var name: String {
        get {
            return "Amsterdam Airport Schiphol"
        }
    }
    
    override open var location: AirportLocation {
        get {
            return AirportLocation(latitude: 52.308601, longitude: 4.76389)
        }
    }
    
    override open var municipality: String {
        get {
            return "Amsterdam"
        }
    }
    
    override open var IATACode: String {
        get {
            return "AMS"
        }
    }
    
    override open var ICAOCode: String {
        get {
            return "EHAM"
        }
    }
    
    override open var size: AirportSize {
        get {
            return .large
        }
    }
}
