load('//buck-macro:utils.bzl',
    'bundle_identifier',
    'info_plist_substitutions',
    'app_binary_configs',
    'app_test_configs',
    'library_configs'
)

apple_asset_catalog(
    name = "QCourseAssets",
    visibility = ["//App:"],
    app_icon = "AppIcon",
    dirs = ["Assets.xcassets"],
)

apple_resource(
    name = "QCourseAppResource",
    visibility = ["//App:"],
    files = glob(["**/*.storyboard"]),
)

apple_binary(
    name = "QCourseAppBinary",
    visibility = [
        "//App:",
        "//App/...",
    ],
    swift_version = "5",
    configs = app_binary_configs("QCourse"),
    srcs = [
        "AppDelegate.swift",
        "ViewController.swift",
        "GeoUtils.m",
        "Airport.swift",
        "TPE.swift",
        "AMS.swift",
    ],
    bridging_header = "QCourse-Bridging-Header.h",
    headers = [
        "GeoUtils.h"
    ],
    deps = [
        ":QCourseAppResource",
        ":QCourseAssets",

    # Pods
        "//Pods:AppDevKit",
    ]
)

apple_bundle(
    name = "QCourse",
    visibility = [
        "//App:",
    ],
    extension = "app",
    binary = ":QCourseAppBinary",
    product_name = "QCourseApp",
    info_plist = "Info.plist",
    info_plist_substitutions = info_plist_substitutions("QCourseApp"),
    tests = [
        ":QCourseUnitTest",
    ],
)

apple_package(
    name = "QCoursePackage",
    bundle = ":QCourse"
)

xcode_workspace_config(
    name = "QCourseWorkspace",
    workspace_name = "QCourse",
    src_target = ":QCourse",
    additional_scheme_actions = {
        'Build': {
            'PRE_SCHEME_ACTIONS': ["echo 'Started'"],
            'POST_SCHEME_ACTIONS': ["echo 'Finished'"],
        },
    }
)



apple_test(
    name = "QCourseUnitTest",
    visibility = ["PUBLIC"],
    info_plist = "UnitTests/Info.plist",
    info_plist_substitutions = {
      "CURRENT_PROJECT_VERSION": "1",                                
      "DEVELOPMENT_LANGUAGE": "en",
      "EXECUTABLE_NAME": "QCourseUnitTest",
      "PRODUCT_BUNDLE_IDENTIFIER": "tw.qcl.QCourseUnitTest",
      "PRODUCT_NAME": "QCourseUnitTest",
    },
    destination_specifier = None,
    test_host_app = None,
    is_ui_test = False,
    ui_test_target_app = None,
    run_test_separately = False,
    configs = app_test_configs("QCourseUnitTest"),
    frameworks = [
        "$PLATFORM_DIR/Developer/Library/Frameworks/XCTest.framework"
    ],
    swift_version = "5",
    srcs = ["UnitTests/QCourseTests.swift"]
)
