//
//  TPE.swift
//  QCourse
//
//  Created by Qing-Cheng Li on 2019/9/5.
//  Generated by script
//  Copyright © 2019 Qing-Cheng Li. All rights reserved.
//

import Foundation

open class TPE: Airport {
    override open var name: String {
        get {
            return "Taiwan Taoyuan International Airport"
        }
    }

    override open var location: AirportLocation {
        get {
            return AirportLocation(latitude: 25.0777, longitude: 121.233002)
        }
    }
    
    override open var municipality: String {
        get {
            return "Taipei"
        }
    }
    
    override open var IATACode: String {
        get {
            return "TPE"
        }
    }
    
    override open var ICAOCode: String {
        get {
            return "RCTP"
        }
    }
    
    override open var size: AirportSize {
        get {
            return .large
        }
    }
}
